import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "../sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Product",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar/>
        {children}
        </body>
    </html>
  );
}
